apiVersion: v1
kind: Secret
metadata:  
  name: frontend-app-secret-2
type: Opaque
data:
  #api_url: <BASE64_ENCODED_IP:PORT_FOR_backend-app-service>
  api_url: MTkyLjE2OC4zMC4zODo1MDAw

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment-2
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - backend-app
              topologyKey: kubernetes.io/hostname
      containers:
        - name: frontend-app
          image: jswolf059/developer-utilities-frontend
          ports:
            - containerPort: 5000
          env:
          - name: API_URL
            valueFrom:
              secretKeyRef:
                name: frontend-app-secret
                key: api_url
                optional: false 
      imagePullSecrets:
      - name: docker-hub-creds
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service-2
spec:
  selector:
    app: frontend-app
  ports:
    - name: web-app-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer