apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
  namespace: namespace-1
spec:
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
        - 192.168.128.0/18
      serviceDomain: managedcluster.local
      services:
        cidrBlocks:
        - 192.168.192.0/18
  topology:
    controlPlane:
      replicas: 1
      storageClass: k8s-storage-policy
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      vmClass: best-effort-small
    nodePools:
    - name: worker-nodepool-1    
      replicas: 2
      storageClass: k8s-storage-policy
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      vmClass: best-effort-small